// Embeds level.json into src/core/embedded-level.js as a JS string
// constant. Re-running this script regenerates the embedded module.
import { readFileSync, writeFileSync } from 'node:fs';

const LEVEL_PATH = '../levels/the-architect/level.json';
const OUT_PATH   = '../src/core/embedded-level.js';

const raw = readFileSync(LEVEL_PATH, 'utf-8');
// Parse + re-stringify to normalize; embed as a JS string we then JSON.parse
// at runtime. Using JSON.stringify on the result gives us a valid JS string
// literal with all escaping handled correctly.
const parsed = JSON.parse(raw);
const embedded = JSON.stringify(parsed);
const stringLiteral = JSON.stringify(embedded);

const out = `// src/core/embedded-level.js — the architect level, baked into the
// bundle. Generated by build-tools/embed-level.mjs at build time so the
// engine receives the level synchronously instead of fetching it — needed
// for file:// double-click play of the bundled game.
export const GAME_SLUG = 'the-architect';
export const GAME_LEVEL = JSON.parse(${stringLiteral});
`;

writeFileSync(OUT_PATH, out);
console.log('Embedded level. Bytes:', embedded.length);
