// Bundles all referenced story files into a single JS module that
// the narration system loads from instead of fetching `/api/story-load`.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const STORIES_DIR = 'D:/V3D Dev/stories';
const OUT = '../src/core/embedded-stories.js';

const stories = {};
for (const fname of readdirSync(STORIES_DIR)) {
  if (!fname.endsWith('.json')) continue;
  if (!fname.startsWith('story-architect-')) continue;
  const id = fname.replace(/\.json$/, '');
  const data = JSON.parse(readFileSync(join(STORIES_DIR, fname), 'utf-8'));
  stories[id] = data;
}

const json = JSON.stringify(stories);
const out = `// src/core/embedded-stories.js — all 12 architect stories,
// baked into the bundle. Generated by build-tools/embed-stories.mjs.
export const GAME_STORIES = JSON.parse(${JSON.stringify(json)});
`;
writeFileSync(OUT, out);
console.log('Embedded', Object.keys(stories).length, 'stories.');
